noinst_HEADERS= AbstractComChannel.hh \
                AbstractInterp4Command.hh \
                AbstractMobileObj.hh \
                AbstractScene.hh \
                AccessControl.hh \
                Configuration.hh \
                Cube.hh \
                CubeObj.hh \
                ExecPreprocesor.hh \
                geomVector.hh \
                LibInterface.hh \
                Port.hh \
                ProgramInterpreter.hh \
                Scene.hh \
                Sender.hh \
                Set4LibInterfaces.hh \
                Vector3D.hh \
                xmlinterp.hh \
                Interp4Move.hh \
                Interp4Pause.hh \
                Interp4Rotate.hh \
                Interp4Set.hh 